### ISSUE TITLE
upload failure

### ISSUE THREAD

**Issue by dstern** [Morwey/ezreverse#1]
On both Firefox and Chrome, website fails to upload file
<img width="1465" alt="image" src="https://github.com/Morwey/ezreverse/assets/836143/4a2f222e-867d-4e22-8260-b8b49ab9afed">

Update: This may be a MacOSX issue, since I am not encountering this error in Windows.

**Comment by JoachimGoedhart** [comment]
Thanks for the interest in the app!
Currently PDF is not supported. You can either generate a screenshot and upload that or export the PDF to a bitmap format like PNG or JPEG. Let us know if that works.
