### ISSUE TITLE
Random image (dog conditioning) suddely appeared in "reversed image" box

### ISSUE THREAD

**Issue by Sverreg** [Morwey/ezreverse#2]
Thanks for the super useful app! 

This is a strange bug, no idea how it happened. I tried to reverse a UMAP image, and wanted to try the different color space options. I did so impatiently, and at first I got an error I unfortunately cannot reproduce or remember - then I ended up with the pictures below. The input image is attached. Could this be another user's uploaded image? The "original image" occasionally reverts to the default image. This happens more frequently when I switch between color spaces.

![image](https://github.com/Morwey/ezreverse/assets/27206049/33342d3a-69c8-4556-8594-ce5051ad5772)
![ABCAtlas_10x scRNAseq whole brain_UMAP](https://github.com/Morwey/ezreverse/assets/27206049/78b281d5-fd54-47f6-a259-813b70270119)

**Comment by JoachimGoedhart** [comment]
Thanks Sverre for the enthusiasm and wow, that is a weird bug!
Usually the shiny apps use different sessions for different users, but this looks indeed like another users data (it's not data that is part of the app). I haven't seen this before, so I'm not sure whether this is specific for a Python-based app, although I would assume that also in these cases the sessions are isolated.
Not sure if I can prevent this, but I appreciate it when you (or other users) notify us when this happens in the future!

Cheers, Joachim.

**Comment by Morwey** [comment]
Hi Sverreg,
Thank you very much for letting us know! This issue occurred due to an unexpected resource allocation when many users used the app simultaneously. The code is updated, and the latest version should now prevent this from happening again.
